name = "MathProgBase"
uuid = "fdba3010-5040-5b88-9595-932c9decdf73"
repo = "https://github.com/JuliaOpt/MathProgBase.jl.git"
version = "0.7.8"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "~0, ~1, ~2"
julia = "~0.6, ~0.7, ~1"

[extras]
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
GLPKMathProgInterface = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"

[targets]
test = ["GLPKMathProgInterface", "ECOS", "Ipopt"]
